# This is a basic workflow to help you get started with Actions

name: Integration Tests

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
    grobid:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: lfoppiano/grobid:0.7.2
                options: -p 8070:8070
                run: |   
                    /tini -s -- ./grobid-service/bin/grobid-service
    pdfanalyzer:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: pip install --upgrade pip && pip install -r deliverable1/requirements.txt
        - name: run tests
          run: python -m unittest deliverable1.test.test_analyzer