# This is a basic workflow to help you get started with Actions

name: Integration Tests

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  grobid:
    name: Grobid Image
    runs-on: ubuntu-latest
    container:
      image: lfoppiano/grobid:0.7.2
      ports:
        - "8070:8070"

  pdfanalyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - env:
          GITHUB_TOKEN: ${{ secrets.OPENSCIENCE_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install --upgrade pip && pip install -r deliverable1/requirements.txt
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: run tests
        run: python -m unittest deliverable1.test.test_analyzer